#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# generate-sidebar.sh
# Regenerates _sidebar.md for the docsify local site.
# Scans engagements/ for all customers (skipping _template) and builds
# navigation entries from their context, tasks, outputs, calls, and docs.
#
# Usage:  ./scripts/generate-sidebar.sh
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/_sidebar.md"

# ── Helper: turn a filename into a readable label ────────────────────
label_from_file() {
  local name
  name="$(basename "$1" .md)"
  # Strip leading numbers + dash (e.g. "01-pod-crash" → "Pod Crash")
  name="${name#[0-9][0-9]-}"
  # Replace dashes with spaces and title-case
  echo "$name" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1'
}

# ── Static sections ─────────────────────────────────────────────────
cat > "$OUT" << 'STATIC'
<!-- Auto-generated by scripts/generate-sidebar.sh — do not hand-edit -->

- **Home**
  - [Overview](README.md)

- **Skills**
STATIC

# Skills
for f in "$ROOT"/skills/*.md; do
  [ -f "$f" ] || continue
  echo "  - [$(label_from_file "$f")](skills/$(basename "$f"))" >> "$OUT"
done

cat >> "$OUT" << 'TEMPLATES'

- **Templates**
TEMPLATES

# Templates
for f in "$ROOT"/templates/*.md; do
  [ -f "$f" ] || continue
  echo "  - [$(label_from_file "$f")](templates/$(basename "$f"))" >> "$OUT"
done

# ── Demo assets ─────────────────────────────────────────────────────
if [ -d "$ROOT/demo-assets" ] && [ "$(find "$ROOT/demo-assets" -mindepth 1 -maxdepth 1 -type d 2>/dev/null)" ]; then
  echo "" >> "$OUT"
  echo "- **Demo Assets**" >> "$OUT"
  # Top-level summary (README.md)
  [ -f "$ROOT/demo-assets/README.md" ] && \
    echo "  - [Summary](demo-assets/README.md)" >> "$OUT"
  for demo_dir in "$ROOT"/demo-assets/*/; do
    [ -d "$demo_dir" ] || continue
    demo_name="$(basename "$demo_dir")"
    demo_label="$(echo "$demo_name" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1')"
    echo "  - **${demo_label}**" >> "$OUT"
    for f in "$demo_dir"*.md; do
      [ -f "$f" ] || continue
      echo "    - [$(label_from_file "$f")](demo-assets/${demo_name}/$(basename "$f"))" >> "$OUT"
    done
  done
fi

# ── Product intelligence ─────────────────────────────────────────────
if [ -d "$ROOT/products" ]; then
  echo "" >> "$OUT"
  echo "- **Products**" >> "$OUT"
  [ -f "$ROOT/products/README.md" ] && \
    echo "  - [Overview](products/README.md)" >> "$OUT"
  for product_dir in "$ROOT"/products/*/; do
    [ -d "$product_dir" ] || continue
    product_name="$(basename "$product_dir")"
    product_label="$(echo "$product_name" | tr '[:lower:]' '[:upper:]' | sed 's/-/ /g')"
    has_product_files=false
    for f in "$product_dir"*.md; do
      [ -f "$f" ] || continue
      if [ "$has_product_files" = false ]; then
        echo "  - **${product_label}**" >> "$OUT"
        has_product_files=true
      fi
      echo "    - [$(label_from_file "$f")](products/${product_name}/$(basename "$f"))" >> "$OUT"
    done
  done
fi

# ── Customer engagements ────────────────────────────────────────────
echo "" >> "$OUT"
echo "- **Engagements**" >> "$OUT"

for customer_dir in "$ROOT"/engagements/*/; do
  customer="$(basename "$customer_dir")"
  [ "$customer" = "_template" ] && continue

  customer_upper="$(echo "$customer" | tr '[:lower:]' '[:upper:]')"
  echo "  - **${customer_upper}**" >> "$OUT"

  # Context & tasks
  [ -f "$customer_dir/context.md" ] && \
    echo "    - [Context](engagements/${customer}/context.md)" >> "$OUT"
  [ -f "$customer_dir/tasks.md" ] && \
    echo "    - [Tasks](engagements/${customer}/tasks.md)" >> "$OUT"

  # Outputs (top-level .md files)
  has_outputs=false
  for f in "$customer_dir"/outputs/*.md; do
    [ -f "$f" ] || continue
    if [ "$has_outputs" = false ]; then
      echo "    - **Outputs**" >> "$OUT"
      has_outputs=true
    fi
    echo "      - [$(label_from_file "$f")](engagements/${customer}/outputs/$(basename "$f"))" >> "$OUT"
  done

  # Outputs — subdirectories (e.g. demo-assets/byok-runbooks)
  last_subdir=""
  find "$customer_dir/outputs" -mindepth 2 -name '*.md' 2>/dev/null | sort | while read -r f; do
    rel="${f#"$customer_dir"/outputs/}"
    subdir="$(dirname "$rel")"
    subdir_label="$(echo "$subdir" | sed 's|/| / |g; s/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1')"
    if [ "$subdir" != "$last_subdir" ]; then
      echo "    - **${subdir_label}**" >> "$OUT"
      last_subdir="$subdir"
    fi
    echo "      - [$(label_from_file "$f")](engagements/${customer}/outputs/${rel})" >> "$OUT"
  done

  # Call notes
  has_calls=false
  for f in "$customer_dir"/reference/calls/*.md; do
    [ -f "$f" ] || continue
    if [ "$has_calls" = false ]; then
      echo "    - **Call Notes**" >> "$OUT"
      has_calls=true
    fi
    echo "      - [$(label_from_file "$f")](engagements/${customer}/reference/calls/$(basename "$f"))" >> "$OUT"
  done

  # Reference docs
  has_docs=false
  for f in "$customer_dir"/reference/docs/*.md; do
    [ -f "$f" ] || continue
    if [ "$has_docs" = false ]; then
      echo "    - **Reference Docs**" >> "$OUT"
      has_docs=true
    fi
    echo "      - [$(label_from_file "$f")](engagements/${customer}/reference/docs/$(basename "$f"))" >> "$OUT"
  done

  # Reference data
  has_data=false
  for f in "$customer_dir"/reference/data/*.md; do
    [ -f "$f" ] || continue
    if [ "$has_data" = false ]; then
      echo "    - **Reference Data**" >> "$OUT"
      has_data=true
    fi
    echo "      - [$(label_from_file "$f")](engagements/${customer}/reference/data/$(basename "$f"))" >> "$OUT"
  done

  # Reference links
  has_links=false
  for f in "$customer_dir"/reference/links/*.md; do
    [ -f "$f" ] || continue
    if [ "$has_links" = false ]; then
      echo "    - **Links**" >> "$OUT"
      has_links=true
    fi
    echo "      - [$(label_from_file "$f")](engagements/${customer}/reference/links/$(basename "$f"))" >> "$OUT"
  done

  # Shadowbot inputs
  has_shadowbot=false
  for f in "$customer_dir"/reference/shadowbot/*.md; do
    [ -f "$f" ] || continue
    if [ "$has_shadowbot" = false ]; then
      echo "    - **Shadowbot**" >> "$OUT"
      has_shadowbot=true
    fi
    echo "      - [$(label_from_file "$f")](engagements/${customer}/reference/shadowbot/$(basename "$f"))" >> "$OUT"
  done
done

echo "✓ Sidebar regenerated: $OUT"
